name: Automated tests

# Go when
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
          type: choice
          options:
            - first_test
            - second_test

# Which virtual container will be using for the tests starting
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: first test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest -v -s test_base_page.py::test_click_homepage
      - name: second test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest -v -s test_base_page.py::test_click_single_elements
