name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
          type: choice
          options:
            - test_first
            - test_second

# Which virtual container will be using for the tests starting
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test_first
        if: "github.event.inputs.deployment_target == 'test_first'"
        run: pytest -v -s test_base_page.py::test_first
      - name: test_second
        if: "github.event.inputs.deployment_target == 'test_second'"
        run: pytest -v -s test_base_page.py::test_second
